### PR TITLE
Delete broken readiness/liveness probe functionality

### PR DESCRIPTION
**Pull request by msrb**

### CODE REVIEW

**Comment by msrb** [comment]
This seems to be working nicely :)

**Comment by msehnout** [comment]
What exactly is the point of running `true` in a container? Is it related to the application state in any way?

**Comment by msrb** [comment]
> What exactly is the point of running true in a container? Is it related to the application state in any way?

It is not. We can replace it with whatever we want in future. The previous implementation was completely broken.

**Comment by msehnout** [comment]
ok, in that case LGTM

**Pull request merged**
